spring.application.name=Corporate
server.port=9876

spring.datasource.url=jdbc:mariadb://localhost:3306/fleet_manager
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Explicitly set the dialect to avoid detection errors
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true